Improve the Kube Review Prune project to check the review envs non-ephemerals
FindHotel/kube-review pull request #109
Opened 2022-07-04 10:13 UTC by reeve24

2022-07-05 07:56 UTC, victorpoluceno requested changes
I left a comment about the implementation. Also, I think we need a description for the PR and a link to the shortcut ticket, so we know what this is about.

2022-07-05 07:56 UTC, victorpoluceno commented on src/prune/main.go
> +			expired = true
I think that what we discussed was that we need a new expiration duration for the non-ephemeral envs. This new duration should be bigger than the one for ephemeral envs, like one month. So, if a review env is non-ephemeral and has not seen any updates in more than one month, it will be purged.

So, you need to add a new config option for the duration and perform the check here.

2022-07-06 13:13 UTC, victorpoluceno requested changes

2022-07-06 13:13 UTC, victorpoluceno commented on src/prune/main.go
> -		expired := time.Since(*namespace.UpdatedAt) >= time.Duration(c.Int("expiration"))*time.Hour
I think this will be cleaner if you do:

```
expiration := time.Duration(c.Int("expiration"))*time.Hour
if !namespace.IsEphemeral {
    expiration = time.Duration(c.Int("nonEphemeralExpiration"))*time.Hour
}
```

then we can use the same block of code for checking.

2022-07-06 13:13 UTC, victorpoluceno commented on src/prune/main.go
> +			Usage: "how many hours to consider an ephimeral environment stale",
ephimeral -> ephemeral

2022-07-11 09:10 UTC, reeve24 commented
Results after DryRun: 

`2022/07/11 10:59:56 Name: re-core-temp-ra-30574c43 Duration: 3262h16m45.974883s, Expired: true, Merged: true, Ephemeral: false
2022/07/11 10:59:56 K8s namespace deleted: re-core-temp-ra-30574c43`

I could only find one case that meets the conditions

2022-07-11 09:16 UTC, rlinstorres approved these changes
🚀

2022-07-11 12:27 UTC, merged