[sc-59294] Creaging the httpscaledobject file the for Keda project
FindHotel/kube-review pull request #127
Opened 2023-03-27 14:07 UTC by rlinstorres

https://app.shortcut.com/findhotel/story/59294/research-and-poc-a-way-to-sleep-and-wake-pods-for-review-envs

- `httpscaledobject.yml` file created;
- `kustomization.yaml` file updated by adding a new `patch` setting and the `httpscaledobject` file;

2023-03-30 13:34 UTC, rlinstorres commented on Dockerfile
> +RUN curl --proto "=https" -L --silent https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/${KUSTOMIZE_VERSION}/kustomize_${KUSTOMIZE_VERSION}_linux_amd64.tar.gz -o kustomize.tar.
I'm fixing a report from Sonarcloud.

<img width="562" alt="Screenshot 2023-03-30 at 3 33 43 PM" src="https://user-images.githubusercontent.com/11336131/228853022-c6490c62-9d3a-4dfa-8826-f51dd2b5972c.png">

2023-04-04 15:21 UTC, victorpoluceno requested changes
I left some comments. Besides those, I missing update the docs about adding instruction on how to install keda and how to use or no kead.

2023-04-04 15:21 UTC, victorpoluceno commented on src/deploy/deploy
> +  # If e2e environment, we use the default ingress settings
Is this a temp solution? I don't think we should do it like this but have an overlay especially fo e2e where we don't use keda.

2023-04-04 15:21 UTC, victorpoluceno commented on src/deploy/resources/base/ingress-keda/httpscaledobject.yml
> +  targetPendingRequests: 100
What is this used for?

2023-04-04 15:21 UTC, victorpoluceno commented on src/deploy/resources/base/kustomization.yaml
> +  - path: patches/httpscaledobject.patch.json
Why do we need to both ingress patches?

2023-04-05 07:38 UTC, rlinstorres commented
> I left some comments. Besides those, I missing update the docs about adding instruction on how to install keda and how to use or no kead.

Sure, I will update our docs.

2023-04-05 07:48 UTC, rlinstorres commented on src/deploy/resources/base/kustomization.yaml
> +  - path: patches/httpscaledobject.patch.json
Because we need to specify the review env URL in each `ingress.yml` and `httpscaledobject.yml` files when used/configured. We will not use both at the same time, for example: For e2e envs, we will use only `ingress.yml` file and for review envs, we will use only `httpscaledobject.yml` for Keda to collect HTTP metrics.

2023-04-05 07:49 UTC, rlinstorres commented on src/deploy/resources/base/ingress-keda/httpscaledobject.yml
> +  targetPendingRequests: 100
For Keda to collect HTTP metrics from the envs.
ref.: https://github.com/kedacore/http-add-on/blob/main/docs/ref/v0.2.0/http_scaled_object.md

2023-04-05 07:53 UTC, rlinstorres commented on src/deploy/deploy
> +  # If e2e environment, we use the default ingress settings
I understand, but I'm still working on it, trying to identify a good approach to dealing with it.

2023-04-05 14:14 UTC, rlinstorres commented on src/deploy/resources/base/kustomization.yaml
> +  name: kube-review
Setting the correct label to be filtered in the Spot.io UI to check the costs per each namespace.

2023-04-06 10:01 UTC, rlinstorres commented on src/deploy/resources/base/kustomization.yaml
> +  - path: patches/httpscaledobject.patch.json
As we discussed, we only need to have `httpscaledobject` configured.

2023-04-13 19:04 UTC, victorpoluceno requested changes

2023-04-13 19:04 UTC, victorpoluceno commented on src/deploy/deploy
> +    cd "$work_dir"
I think it needs to be `cd "$work_dir/base"` otherwise you are breaking the use case when there is no custom overlay. I think this will also remove the need for the `cd` that you are doing bellow.

2023-04-17 13:54 UTC, rlinstorres commented on src/deploy/deploy
> +  cd "$work_dir"
I agree, I've updated the bash script

2023-04-17 13:54 UTC, rlinstorres commented on src/deploy/deploy
> +    cd "$work_dir"
I agree, I've updated the bash script

2023-04-17 22:38 UTC, victorpoluceno commented on src/deploy/deploy
> +  if [ "$verbose" = "true" ]; then
hmm, I'm not sure if I get it. How come if the two lines are the same:

```
   kustomize build | kubectl apply -f - -n "$namespace" --wait=true
  else
    kustomize build | kubectl apply -f - -n "$namespace" --wait=true
```

2023-04-18 09:54 UTC, rlinstorres commented on src/deploy/deploy
> +  if [ "$verbose" = "true" ]; then
Sorry, you are right! I've tested it and the result is the same, so checking our current `deploy` script in the master branch, we have this setting and my idea was to use the same approach:

https://github.com/FindHotel/kube-review/blob/master/src/deploy/deploy#L108

I've updated the script again removing this setting.

2023-04-18 13:50 UTC, victorpoluceno commented on src/deploy/deploy
> +  if [ "$verbose" = "true" ]; then
Yeah, that works. You should keep that line that you removed: https://github.com/FindHotel/kube-review/pull/127/files#diff-c8603b35c42bb511679102a64c3632f705fa98234f07d7d3818de749fa8d9eeaL108

2023-04-18 14:22 UTC, rlinstorres commented on src/deploy/deploy
> +  if [ "$verbose" = "true" ]; then
Done!

2023-04-21 11:27 UTC, victorpoluceno approved these changes

2023-04-24 12:25 UTC, merged