[ch33428] - dockerhub secret configured
FindHotel/kube-review pull request #69
Opened 2021-05-12 09:36 UTC by rlinstorres

https://app.clubhouse.io/findhotel/story/33428/kube-review-connection-test-fails-with-docker-hub-rate-limit-error

2021-05-13 17:28 UTC, victorpoluceno requested changes

2021-05-13 17:28 UTC, victorpoluceno commented on deploy/deploy
> +  kubectl get secret $dockerhub_secret_name -n default -o yaml | sed s/"namespace: default"/"namespace: $namespace"/\
I don't see how this will keep working if you delete the docker hub secrets from the default service account this will stop working. Besides, this seems a bit of a hack. 

My suggestion, create the `ImagePullSecrets` using terraform using a well know name. So you can keep the secrets stored as secrets on CodeFresh. Then, on the service account you only need to reference the `ImagePullSecrets` as you are already doing.

2021-05-17 15:16 UTC, victorpoluceno approved these changes
awesome!

2021-05-18 16:45 UTC, gtonello approved these changes
LGTM

2021-05-19 21:33 UTC, victorpoluceno approved these changes

2021-05-19 23:45 UTC, gtonello approved these changes

2021-05-20 14:57 UTC, merged