[ch31794] - kube-review deploy parameters updated
FindHotel/kube-review pull request #71
Opened 2021-06-07 09:01 UTC by rlinstorres

https://app.clubhouse.io/findhotel/story/31794/improve-kube-review-deploy-parameters

2021-06-08 12:36 UTC, gtonello approved these changes

2021-06-09 09:16 UTC, rlinstorres commented on deploy/deploy
> -  CUSTOM_envFrom_secretRef_name="$namespace" \
This parameter we do not need to pass by default in all deployments because we have a parameter in our chart to enable it in `values.yaml` file if necessary.

2021-06-09 13:59 UTC, victorpoluceno requested changes

2021-06-09 13:59 UTC, victorpoluceno commented on charts/kube-review/templates/deployment.yaml
> +            # So, it's better to only expose one host.
so me

2021-06-09 13:59 UTC, victorpoluceno commented on deploy/deploy
> +dockerhub_secret_copy_enabled=${KR_DOCKERHUB_SECRET_COPY_ENABLED:-true}
I think it should be disabled by default.

2021-06-09 14:39 UTC, rlinstorres commented on deploy/deploy
> +dockerhub_secret_copy_enabled=${KR_DOCKERHUB_SECRET_COPY_ENABLED:-true}
Done!

2021-06-09 15:36 UTC, victorpoluceno approved these changes

2021-06-10 09:13 UTC, merged