Changing IMAGE field to use only one argument as a value
FindHotel/kube-review pull request #86
Opened 2021-09-20 14:47 UTC by rlinstorres

Changing `Kube-Review` deployment file to use only one argument in `Container Image`, making it possible to use a full URL of Image URL repository.

2021-09-20 17:07 UTC, gtonello approved these changes
LGTM. Don't forget to create a new release.

2021-09-23 09:00 UTC, victorpoluceno requested changes

2021-09-23 09:11 UTC, rlinstorres commented on docs/reference.md
> +| KR_IMAGE | The full url of the container image, including the tag that the app should run. e.g: `KR_IMAGE=123456789012.dkr.ecr.eu-west-1.amazonaws.com/ecr-repo-name@sha256:2de5d881318951e48c69987df
I see, but it is not related to our Infra, there is a random number here `123456789012.dkr.ecr.eu-west-1.amazonaws.com`

2021-09-23 12:34 UTC, gtonello commented on docs/reference.md
> +| KR_IMAGE | The full url of the container image, including the tag that the app should run. e.g: `KR_IMAGE=123456789012.dkr.ecr.eu-west-1.amazonaws.com/ecr-repo-name@sha256:2de5d881318951e48c69987df
Maybe the example is not necessary?

2021-09-23 13:17 UTC, rlinstorres commented on docs/reference.md
> +| KR_IMAGE | The full url of the container image, including the tag that the app should run. e.g: `KR_IMAGE=123456789012.dkr.ecr.eu-west-1.amazonaws.com/ecr-repo-name@sha256:2de5d881318951e48c69987df
Sure, I changed it to `KR_IMAGE=nginx:stable`

2021-09-23 14:13 UTC, victorpoluceno commented on .github/workflows/ci.yaml
> +          HELM_EXPERIMENTAL_OCI=1 helm push $PACKAGE remote
Why did you had to add this?

2021-09-23 14:13 UTC, victorpoluceno commented on src/deploy/resources/base/patches/deployment.patch.json
> +        "value": "$KR_IMAGE"
You might want to double check that this variable is not used in any overlay in the cf-pipelines repo.

2021-09-23 14:20 UTC, rlinstorres commented on .github/workflows/ci.yaml
> +          HELM_EXPERIMENTAL_OCI=1 helm push $PACKAGE remote
Today an error started to happen: https://github.com/FindHotel/kube-review/runs/3688014268?check_suite_focus=true

<img width="968" alt="Screen Shot 2021-09-23 at 4 20 39 PM" src="https://user-images.githubusercontent.com/11336131/134524589-9ae3fcb1-8e9a-457f-ba4e-0dc4b8bd7421.png">

2021-09-24 08:28 UTC, rlinstorres commented on .github/workflows/ci.yaml
> +          HELM_EXPERIMENTAL_OCI=1 helm push $PACKAGE remote
I changed `github workflows` to fix this error, see PR description.

2021-09-27 13:45 UTC, victorpoluceno approved these changes

2021-09-27 13:45 UTC, victorpoluceno commented on .github/workflows/cd.yaml
> +          #helm push $PACKAGE remote
Better to just remove this line.

2021-09-27 13:51 UTC, merged